#! /usr/bin/php
<?php

define("ICEBERG_LOG", __DIR__."/iceberg.log");
define("ICEBERG_CONFIG", __DIR__."/config.ini");

include __DIR__."/lib/iceberg/Autoloader.php";
include __DIR__."/lib/iceberg/ErrorHandler.php";

use iceberg\Autoloader;
use iceberg\ErrorHandler;

use iceberg\hook\Hook;
use iceberg\cmd\Command;
use iceberg\config\Config;
use iceberg\shell\ArgumentParser;

if (!ini_get('date.timezone'))
	date_default_timezone_set("Europe/Berlin");

ErrorHandler::register(ICEBERG_LOG);

Autoloader::register();
Autoloader::addNamespace("iceberg", __DIR__."/lib/iceberg");
Autoloader::addNamespace("hooks", __DIR__."/hooks");
Autoloader::addNamespace("commands", __DIR__."/lib");

$arguments = ArgumentParser::getInstance();

Config::loadFromFile($arguments->config_val ? $arguments->config_val : ICEBERG_CONFIG);

date_default_timezone_set(Config::getVal("general", "timezone", true));

Hook::setNamespace("hooks\{hook}Hook");

if ($arguments->no_hook) 
	Hook::setEnabled(false);
	
Command::setNamespace("commands\{command}");
Command::call($argv[1]);