#! /usr/bin/php
<?php

define("ICEBERG_LOG", "iceberg.log");
define("ICEBERG_CONFIG", "config.ini");
define("ICEBERG_HOOK", "hooks.json");

include __DIR__."/lib/iceberg/Autoloader.php";
include __DIR__."/lib/iceberg/ErrorHandler.php";

use iceberg\Autoloader;
use iceberg\ErrorHandler;

use iceberg\hook\Hook;
use iceberg\cmd\Command;
use iceberg\config\Config;
use iceberg\shell\ArgumentParser;

if (!ini_get('date.timezone')) {
	date_default_timezone_set("Europe/Berlin");
}

ErrorHandler::register(__DIR__."/".ICEBERG_LOG);

Autoloader::register();
Autoloader::addNamespace("iceberg", __DIR__."/lib/iceberg");
Autoloader::addNamespace("commands", __DIR__."/lib");

$arguments = ArgumentParser::getInstance();

Config::loadFromFile($arguments->config_val ? $arguments->config_val : __DIR__."/".ICEBERG_CONFIG);

date_default_timezone_set(Config::getVal("general", "timezone", true));

if ($arguments->version) {
	echo "Iceberg development release from github/cyrilmengin/iceberg.", PHP_EOL;
}

Hook::loadFromFile(__DIR__."/".ICEBERG_HOOK);
if ($arguments->no_hook && !$arguments->no_hook_val) {
	Hook::disableAll();
} else if ($arguments->no_hook) {
	$hooks = explode(",", $arguments->no_hook_val);
	foreach ($hooks as $hook) {
		Hook::disable($hook);
	}
}

Command::setNamespace("commands\{command}");
if (substr($argv[1], 0, 2) != "--") {
	Command::call($argv[1]);
}
